### ISSUE TITLE
pcl: fails at do_compile with boost 1.56.0

### ISSUE THREAD

**Issue by bulwahn** [bmwcarit/meta-ros#293]
Since a recent OpenEmbedded-Core commit [1, 2], boost has been updated to 1.56.0, and `bitbake pcl` fails with:

| In file included from [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/detail/xml_parser_utils.hpp:15:0,
|                  from [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/detail/xml_parser_write.hpp:15,
|                  from [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/xml_parser.hpp:15,
|                  from [...]/build/tmp-eglibc/work/armv5te-oe-linux-gnueabi/pcl/1.7.0-r0/pcl-pcl-1.7.0/io/src/lzf_image_io.cpp:45:
| [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/detail/xml_parser_writer_settings.hpp: In instantiation of 'class boost::property_tree::xml_parser::xml_writer_settings<char>':
| [...]/build/tmp-eglibc/work/armv5te-oe-linux-gnueabi/pcl/1.7.0-r0/pcl-pcl-1.7.0/io/src/lzf_image_io.cpp:201:60:   required from here
| [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:38:35: error: 'char' is not a class, struct, or union type
|   typedef typename Str::value_type Ch;
|                                    ^
| [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:40:9: error: 'char' is not a class, struct, or union type
|          xml_writer_settings(Ch inchar = Ch(' '),
|          ^
| [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:50:33: error: 'char' is not a class, struct, or union type
|          typename Str::size_type indent_count;
|                                  ^
| [...]/build/tmp-eglibc/work/armv5te-oe-linux-gnueabi/pcl/1.7.0-r0/pcl-pcl-1.7.0/io/src/lzf_image_io.cpp: In member function 'bool pcl::io::LZFImageWriter::writeParameter(const double&, const string&, const string&)':
| [...]/build/tmp-eglibc/work/armv5te-oe-linux-gnueabi/pcl/1.7.0-r0/pcl-pcl-1.7.0/io/src/lzf_image_io.cpp:201:68: error: no matching function for call to 'boost::property_tree::xml_parser::xml_writer_settings<char>::xml_writer_settings(char, int)'
|    boost::property_tree::xml_writer_settings<char> settings ('\t', 1);
|                                                                     ^
| [...]/build/tmp-eglibc/work/armv5te-oe-linux-gnueabi/pcl/1.7.0-r0/pcl-pcl-1.7.0/io/src/lzf_image_io.cpp:201:68: note: candidates are:
| In file included from [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/detail/xml_parser_utils.hpp:15:0,
|                  from [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/detail/xml_parser_write.hpp:15,
|                  from [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/xml_parser.hpp:15,
|                  from [...]/build/tmp-eglibc/work/armv5te-oe-linux-gnueabi/pcl/1.7.0-r0/pcl-pcl-1.7.0/io/src/lzf_image_io.cpp:45:
| [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:36:11: note: boost::property_tree::xml_parser::xml_writer_settings<char>::xml_writer_settings()
|      class xml_writer_settings
|            ^
| [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:36:11: note:   candidate expects 0 arguments, 2 provided
| [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:36:11: note: boost::property_tree::xml_parser::xml_writer_settings<char>::xml_writer_settings(const boost::property_tree::xml_parser::xml_writer_settings<char>&)
| [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:36:11: note:   candidate expects 1 argument, 2 provided
| [...]/build/tmp-eglibc/work/armv5te-oe-linux-gnueabi/pcl/1.7.0-r0/pcl-pcl-1.7.0/io/src/lzf_image_io.cpp:203:52: error: no matching function for call to 'write_xml(const string&, boost::property_tree::ptree&, std::locale, boost::property_tree::xml_parser::xml_writer_settings<char>&)'
|    write_xml (filename, pt, std::locale (), settings);
|                                                     ^
| [...]/build/tmp-eglibc/work/armv5te-oe-linux-gnueabi/pcl/1.7.0-r0/pcl-pcl-1.7.0/io/src/lzf_image_io.cpp:203:52: note: candidates are:
| In file included from [...]/build/tmp-eglibc/work/armv5te-oe-linux-gnueabi/pcl/1.7.0-r0/pcl-pcl-1.7.0/io/src/lzf_image_io.cpp:45:0:
| [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/xml_parser.hpp:100:10: note: template<class Ptree> void boost::property_tree::xml_parser::write_xml(std::basic_ostream<typename Ptree::key_type::value_type>&, const Ptree&, const boost::property_tree::xml_parser::xml_writer_settings<typename Ptree::key_type>&)
|      void write_xml(std::basic_ostream<
|           ^
| [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/xml_parser.hpp:100:10: note:   template argument deduction/substitution failed:
| [...]/build/tmp-eglibc/work/armv5te-oe-linux-gnueabi/pcl/1.7.0-r0/pcl-pcl-1.7.0/io/src/lzf_image_io.cpp:203:52: note:   candidate expects 3 arguments, 4 provided
|    write_xml (filename, pt, std::locale (), settings);
|                                                     ^
| In file included from [...]/build/tmp-eglibc/work/armv5te-oe-linux-gnueabi/pcl/1.7.0-r0/pcl-pcl-1.7.0/io/src/lzf_image_io.cpp:45:0:
| [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/xml_parser.hpp:124:10: note: void boost::property_tree::xml_parser::write_xml(const string&, const Ptree&, const std::locale&, const boost::property_tree::xml_parser::xml_writer_settings<typename Ptree::key_type>&) [with Ptree = boost::property_tree::basic_ptreestd::basic_string<char, std::basic_string<char> >; std::string = std::basic_string<char>; typename Ptree::key_type = std::basic_string<char>]
|      void write_xml(const std::string &filename,
|           ^
| [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/xml_parser.hpp:124:10: note:   no known conversion for argument 4 from 'boost::property_tree::xml_parser::xml_writer_settings<char>' to 'const boost::property_tree::xml_parser::xml_writer_settingsstd::basic_string<char >&'
| [...]/build/tmp-eglibc/work/armv5te-oe-linux-gnueabi/pcl/1.7.0-r0/pcl-pcl-1.7.0/io/src/lzf_image_io.cpp: In member function 'virtual bool pcl::io::LZFDepth16ImageWriter::writeParameters(const pcl::io::CameraParameters&, const string&)':
| [...]/build/tmp-eglibc/work/armv5te-oe-linux-gnueabi/pcl/1.7.0-r0/pcl-pcl-1.7.0/io/src/lzf_image_io.cpp:221:68: error: no matching function for call to 'boost::property_tree::xml_parser::xml_writer_settings<char>::xml_writer_settings(char, int)'
|    boost::property_tree::xml_writer_settings<char> settings ('\t', 1);
|                                                                     ^
| [...]/build/tmp-eglibc/work/armv5te-oe-linux-gnueabi/pcl/1.7.0-r0/pcl-pcl-1.7.0/io/src/lzf_image_io.cpp:221:68: note: candidates are:
| In file included from [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/detail/xml_parser_utils.hpp:15:0,
|                  from [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/detail/xml_parser_write.hpp:15,
|                  from [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/xml_parser.hpp:15,
|                  from [...]/build/tmp-eglibc/work/armv5te-oe-linux-gnueabi/pcl/1.7.0-r0/pcl-pcl-1.7.0/io/src/lzf_image_io.cpp:45:
| [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:36:11: note: boost::property_tree::xml_parser::xml_writer_settings<char>::xml_writer_settings()
|      class xml_writer_settings
|            ^
| [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:36:11: note:   candidate expects 0 arguments, 2 provided
| [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:36:11: note: boost::property_tree::xml_parser::xml_writer_settings<char>::xml_writer_settings(const boost::property_tree::xml_parser::xml_writer_settings<char>&)
| [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:36:11: note:   candidate expects 1 argument, 2 provided
| [...]/build/tmp-eglibc/work/armv5te-oe-linux-gnueabi/pcl/1.7.0-r0/pcl-pcl-1.7.0/io/src/lzf_image_io.cpp:227:52: error: no matching function for call to 'write_xml(const string&, boost::property_tree::ptree&, std::locale, boost::property_tree::xml_parser::xml_writer_settings<char>&)'
|    write_xml (filename, pt, std::locale (), settings);
|                                                     ^
| [...]/build/tmp-eglibc/work/armv5te-oe-linux-gnueabi/pcl/1.7.0-r0/pcl-pcl-1.7.0/io/src/lzf_image_io.cpp:227:52: note: candidates are:
| In file included from [...]/build/tmp-eglibc/work/armv5te-oe-linux-gnueabi/pcl/1.7.0-r0/pcl-pcl-1.7.0/io/src/lzf_image_io.cpp:45:0:
| [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/xml_parser.hpp:100:10: note: template<class Ptree> void boost::property_tree::xml_parser::write_xml(std::basic_ostream<typename Ptree::key_type::value_type>&, const Ptree&, const boost::property_tree::xml_parser::xml_writer_settings<typename Ptree::key_type>&)
|      void write_xml(std::basic_ostream<
|           ^
| [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/xml_parser.hpp:100:10: note:   template argument deduction/substitution failed:
| [...]/build/tmp-eglibc/work/armv5te-oe-linux-gnueabi/pcl/1.7.0-r0/pcl-pcl-1.7.0/io/src/lzf_image_io.cpp:227:52: note:   candidate expects 3 arguments, 4 provided
|    write_xml (filename, pt, std::locale (), settings);
|                                                     ^
| In file included from [...]/build/tmp-eglibc/work/armv5te-oe-linux-gnueabi/pcl/1.7.0-r0/pcl-pcl-1.7.0/io/src/lzf_image_io.cpp:45:0:
| [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/xml_parser.hpp:124:10: note: void boost::property_tree::xml_parser::write_xml(const string&, const Ptree&, const std::locale&, const boost::property_tree::xml_parser::xml_writer_settings<typename Ptree::key_type>&) [with Ptree = boost::property_tree::basic_ptreestd::basic_string<char, std::basic_string<char> >; std::string = std::basic_string<char>; typename Ptree::key_type = std::basic_string<char>]
|      void write_xml(const std::string &filename,
|           ^
| [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/xml_parser.hpp:124:10: note:   no known conversion for argument 4 from 'boost::property_tree::xml_parser::xml_writer_settings<char>' to 'const boost::property_tree::xml_parser::xml_writer_settingsstd::basic_string<char >&'
| [...]/build/tmp-eglibc/work/armv5te-oe-linux-gnueabi/pcl/1.7.0-r0/pcl-pcl-1.7.0/io/src/lzf_image_io.cpp: In member function 'virtual bool pcl::io::LZFRGB24ImageWriter::writeParameters(const pcl::io::CameraParameters&, const string&)':
| [...]/build/tmp-eglibc/work/armv5te-oe-linux-gnueabi/pcl/1.7.0-r0/pcl-pcl-1.7.0/io/src/lzf_image_io.cpp:282:68: error: no matching function for call to 'boost::property_tree::xml_parser::xml_writer_settings<char>::xml_writer_settings(char, int)'
|    boost::property_tree::xml_writer_settings<char> settings ('\t', 1);
|                                                                     ^
| [...]/build/tmp-eglibc/work/armv5te-oe-linux-gnueabi/pcl/1.7.0-r0/pcl-pcl-1.7.0/io/src/lzf_image_io.cpp:282:68: note: candidates are:
| In file included from [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/detail/xml_parser_utils.hpp:15:0,
|                  from [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/detail/xml_parser_write.hpp:15,
|                  from [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/xml_parser.hpp:15,
|                  from [...]/build/tmp-eglibc/work/armv5te-oe-linux-gnueabi/pcl/1.7.0-r0/pcl-pcl-1.7.0/io/src/lzf_image_io.cpp:45:
| [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:36:11: note: boost::property_tree::xml_parser::xml_writer_settings<char>::xml_writer_settings()
|      class xml_writer_settings
|            ^
| [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:36:11: note:   candidate expects 0 arguments, 2 provided
| [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:36:11: note: boost::property_tree::xml_parser::xml_writer_settings<char>::xml_writer_settings(const boost::property_tree::xml_parser::xml_writer_settings<char>&)
| [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:36:11: note:   candidate expects 1 argument, 2 provided
| [...]/build/tmp-eglibc/work/armv5te-oe-linux-gnueabi/pcl/1.7.0-r0/pcl-pcl-1.7.0/io/src/lzf_image_io.cpp:287:52: error: no matching function for call to 'write_xml(const string&, boost::property_tree::ptree&, std::locale, boost::property_tree::xml_parser::xml_writer_settings<char>&)'
|    write_xml (filename, pt, std::locale (), settings);
|                                                     ^
| [...]/build/tmp-eglibc/work/armv5te-oe-linux-gnueabi/pcl/1.7.0-r0/pcl-pcl-1.7.0/io/src/lzf_image_io.cpp:287:52: note: candidates are:
| In file included from [...]/build/tmp-eglibc/work/armv5te-oe-linux-gnueabi/pcl/1.7.0-r0/pcl-pcl-1.7.0/io/src/lzf_image_io.cpp:45:0:
| [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/xml_parser.hpp:100:10: note: template<class Ptree> void boost::property_tree::xml_parser::write_xml(std::basic_ostream<typename Ptree::key_type::value_type>&, const Ptree&, const boost::property_tree::xml_parser::xml_writer_settings<typename Ptree::key_type>&)
|      void write_xml(std::basic_ostream<
|           ^
| [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/xml_parser.hpp:100:10: note:   template argument deduction/substitution failed:
| [...]/build/tmp-eglibc/work/armv5te-oe-linux-gnueabi/pcl/1.7.0-r0/pcl-pcl-1.7.0/io/src/lzf_image_io.cpp:287:52: note:   candidate expects 3 arguments, 4 provided
|    write_xml (filename, pt, std::locale (), settings);
|                                                     ^
| In file included from [...]/build/tmp-eglibc/work/armv5te-oe-linux-gnueabi/pcl/1.7.0-r0/pcl-pcl-1.7.0/io/src/lzf_image_io.cpp:45:0:
| [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/xml_parser.hpp:124:10: note: void boost::property_tree::xml_parser::write_xml(const string&, const Ptree&, const std::locale&, const boost::property_tree::xml_parser::xml_writer_settings<typename Ptree::key_type>&) [with Ptree = boost::property_tree::basic_ptreestd::basic_string<char, std::basic_string<char> >; std::string = std::basic_string<char>; typename Ptree::key_type = std::basic_string<char>]
|      void write_xml(const std::string &filename,
|           ^
| [...]/build/tmp-eglibc/sysroots/qemuarm/usr/include/boost/property_tree/xml_parser.hpp:124:10: note:   no known conversion for argument 4 from 'boost::property_tree::xml_parser::xml_writer_settings<char>' to 'const boost::property_tree::xml_parser::xml_writer_settingsstd::basic_string<char >&'
| make[2]: **\* [io/CMakeFiles/pcl_io.dir/src/lzf_image_io.cpp.o] Error 1
| make[2]: Leaving directory `[...]/build/tmp-eglibc/work/armv5te-oe-linux-gnueabi/pcl/1.7.0-r0/build'
| make[1]: **\* [io/CMakeFiles/pcl_io.dir/all] Error 2

The issue has been previously already reported and addressed in the pcl issue tracker [3, 4]. With the upstream patch applied the current version, the issue is resolved.

[1] http://cgit.openembedded.org/openembedded-core/commit/meta/recipes-support/boost?id=a6afd754290cecbe57392d13477557051b438817
[2] https://github.com/openembedded/oe-core/commit/a6afd754290cecbe57392d13477557051b438817
[3] https://github.com/PointCloudLibrary/pcl/issues/864
[4] https://github.com/PointCloudLibrary/pcl/commit/c2ad66f36569d64a445dbadeae197264d216d48c
